apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mongodb/statefulset.yaml
  - mongodb/service.yaml
  - mongodb/init-rs-job.yaml
  - reid-db-handler/deployment.yaml
  - reid-db-handler/service.yaml
  - reid-analytics-backend/deployment.yaml
  - reid-analytics-backend/service.yaml
  - reid-worker/configmap.yaml
  - reid-worker/deployment.yaml
  - reid-worker/service.yaml
  - flaresolverr/deployment.yaml
  - flaresolverr/service.yaml
